// Generated by CoffeeScript 1.8.0
(function() {
  define(['editor/furnace-rules'], function() {
    'use strict';
    return ace.define('ace/mode/furnace', function(require, exports, module) {
      var HighlightRules, Mode, TextMode, Tokenizer, oop;
      require('ace/theme/furnace-monokai');
      oop = require('ace/lib/oop');
      TextMode = require('./text').Mode;
      Tokenizer = require('ace/tokenizer').Tokenizer;
      HighlightRules = require('ace/mode/furnace-rules').FurnaceHighlightRules;
      Mode = function() {
        this.$tokenizer = new Tokenizer(new HighlightRules().getRules());
      };
      oop.inherits(Mode, TextMode);
      exports.Mode = Mode;
    });
  });

}).call(this);
