// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var colorBindings, convert, spritesByName;
    colorBindings = {
      'w': 'rgb(255, 255, 255)',
      'b': 'rgb(0, 0, 0)',
      '.': 'rgba(0, 0, 0, 0)'
    };
    spritesByName = {
      '0': '..wwwwwwwwwwwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwwwwwwwwwwb..',
      '1': '.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......\n.......wwb......',
      '2': '..wwwwwwwwwwwb..\n..wwb......wwb..\n..wwb......wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n..wwwwwwwwwwwb..\n..wwb...........\n..wwb...........\n..wwb...........\n..wwb...........\n..wwb...........\n..wwb...........\n..wwb...........\n..wwwwwwwwwwwb..',
      '3': '..wwwwwwwwwwwb..\n..wwb......wwb..\n..wwb......wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n.......wwwwwwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwwwwwwwwwwb..',
      '4': '..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwwwwwwwwwwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..',
      '5': '..wwwwwwwwwwwb..\n..wwb...........\n..wwb...........\n..wwb...........\n..wwb...........\n..wwb...........\n..wwb...........\n..wwwwwwwwwwwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwwwwwwwwwwb..',
      '6': '..wwwwwwwwwwwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb...........\n..wwb...........\n..wwb...........\n..wwb...........\n..wwwwwwwwwwwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwwwwwwwwwwb..',
      '7': '..wwwwwwwwwwwb..\n..wwb......wwb..\n..wwb......wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..',
      '8': '..wwwwwwwwwwwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwwwwwwwwwwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwwwwwwwwwwb..',
      '9': '..wwwwwwwwwwwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwwwwwwwwwwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n...........wwb..\n..wwb......wwb..\n..wwb......wwb..\n..wwwwwwwwwwwb..'
    };
    convert = function(stringedSprites) {
      var key, ret, sprite;
      ret = {};
      for (key in stringedSprites) {
        sprite = stringedSprites[key];
        ret[key] = sprite.split('\n').map(function(line) {
          return {
            s: line
          };
        });
      }
      return ret;
    };
    return {
      colorBindings: colorBindings,
      spritesByName: convert(spritesByName)
    };
  });

}).call(this);

//# sourceMappingURL=Font.map
