// Generated by CoffeeScript 1.8.0
(function() {
  define(['tokenizer/Token'], function(Token) {
    'use strict';
    var TokEnd;
    TokEnd = function(coords) {
      this.coords = coords;
    };
    TokEnd.prototype = Object.create(Token.prototype);
    TokEnd.prototype.constructor = TokEnd;
    TokEnd.prototype.match = function(that) {
      return that instanceof TokEnd;
    };
    TokEnd.prototype.toString = function() {
      return 'END';
    };
    return TokEnd;
  });

}).call(this);
